language: node_js
node_js:
  - '10'

cache: yarn

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH

jobs:
  include:
    - stage: test
      script:
        - yarn build-lib
        - yarn build-demo
        - ./node_modules/.bin/ng test natural --progress false --watch=false --browsers ChromeHeadlessCustom
        - ./node_modules/.bin/ng test demo --progress false --watch=false --browsers ChromeHeadlessCustom
        - yarn lint

    - stage: publish docs
      if: branch IN (master, develop)
      script:
        - yarn build-demo
      deploy:
        provider: pages
        local-dir: dist/demo
        github-token: $GITHUB_TOKEN
        on:
          all_branches: true

    - stage: publish npm package
      if: tag is present
      script:
        - yarn build-lib
      before_deploy:
        - rm .gitignore
        - cd dist/natural
      deploy:
        provider: npm
        edge: true
        email:
          secure: mxgacbX0wedRvCXBjA8vTiqshk3QJ67dwyx/0U9Crzw1kbseBnDMlsTrxJFORiHnW24b6H3XbgW1P//+ATdkEeLS/tzXJ+R9leJLUuUb2YeDdhMSE2h+sZCaB8BtsgC9GJdzzblqIxcRqZhZbbXllmvvjyQkkUsaACwBFs9ENAgkwB5DRZIluyQiFgjtZGXq9M8/J4xC3YYRll32lNGlzt7xErHJGmHgq7qti2PP5ZFReOV0KRl4pi26efywrZx0atnJHsAtyTGCsrfO4o0PzufAOmbHK55I6sGN46egyFRz+qKZD4YeNZqOFei6NpRUsI0vYYmND5FIKDyBVYa69e2OpRe+Ua2eWPpUnYRjgIsCXU2FkkOt7dmx1WqucKqxHo76+PSNssdDSwVhqwVTx4rD5YWGWHK+emNvLniTZEnTKfMpG8QFZtBb8ucSMnagWXVMwYeo1ibv5vgCxHV2+xyKMTqDI7or3Bg+z4PZquzJnYvTnzYeGM1CfbUPPm8QgqjkLmFZnPMrGPYdUUAYDwBYbPb1wSx1a/GLLoWJu2qMzPwjF2IaOlObmvleJoZbT99FoT3Tr+a51RiyQBP11NyFe/OSWVszpRhU77P18UZFafgocCjBhGcLuXuLXUICPUJjQlUdyWoUySWJpLHe1HG1IrRSDo6jX+c2VLxaURk=
        api_key:
          secure: DA0ir347zpbW5vXtD4L2Xyb5CtNpusdr6/MzeEhv1yP/ItpoMkZymFj3QVM1/wjgizgndKKytrsZtcNBpwJNoHguZtTAXgUkcIl25i3afvdbjsWsGH8fEprEatQG9q4uzE23gEa66O8+jzm8ub61y7QK3AJkQFz1yOpggvYQV4ngWSxBYWbji0YljOVXFhZI0RqezMHuzhQza28XI1v0KrFsziLXPJOXZbl31BKkJ+So7ZxQIRMTox+CZ/Bt3jYTJTZbibrAb7J+W7VtdDB24fscp9bxq5qQMG2kkmuX3mpTQl8nZIMU/LA4fGMj0vB1wSRWfITr6kObUWFuGqIg8y3tNQyqTHf/8VVYM297qQB2nZR5ApKnyrIAHJ4BHWwVdJ3TNvVLozcyXjCV0be3MocX2eTicHZE56ErtBpSoRKuLmPgqiNpAaqqCwUZQubunGhIxYQOxB130duxaNO9wXTLJ4oqkHMs74Tjcw8pYbNAKLQaMpo116JT4wjWgnq1N2pqjltKBI9qNp76xK2J6YqIgiXbAV0IdjpV2Psx83tHm3/TkASKrR0LWkTdhTAogRcybyqNCOKBdgGq2xRRGVIPX9UrBDK6L7EffceNpECaeN1ptCsyJtk/kkPorGUUNgrwC0AnKxUhg44Vb7ywXcR+Duji4LW/k04Rcr3MIEk=
        on:
          tags: true
